/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as monoSwapRouterSol from "./MonoSwapRouter.sol";
export type { monoSwapRouterSol };
export type { MonoSwapFactory } from "./MonoSwapFactory";
export type { MonoSwapPair } from "./MonoSwapPair";
export type { MonoToken } from "./MonoToken";
export type { WETH } from "./WETH";
